version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - clickhouse
    restart: on-failure
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - CLICKHOUSE_DB=test
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "--tries=1", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
    networks:
      - app-network

volumes:
  clickhouse-data:

networks:
  app-network:
    driver: bridge