version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ecomet-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecomet-app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE__POSTGRES__HOST=postgres
      - DATABASE__POSTGRES__PORT=5432
      - DATABASE__POSTGRES__USERNAME=postgres
      - DATABASE__POSTGRES__PASSWORD=postgres
      - DATABASE__POSTGRES__DB=postgres
      - LOGGING__LEVEL=DEBUG
      - DEBUG=true

volumes:
  postgres_data: